FROM tensorflow/tensorflow:2.6.0-gpu

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

RUN apt-get update && apt-get install -y cmake wget llvm aria2 unzip
RUN apt-get install -y libxrender-dev && \
    apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev
WORKDIR /root
COPY ./ ./
RUN python -m pip install --upgrade pip
RUN cd /root/src/imagecluster/ && \
    pip3 install -e .
RUN pip3 install -r requirement_gpu.txt
RUN gdown --id 12oyXwsQ3Z0_oRTIQMdzVjCumN7hXaCVH && \
    unzip models.zip
RUN python3 app.py
